# -*- coding: utf-8 -*-
"""chc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eiqOSwpEd9XxGBWapgFJE0DEA4qlmMT5
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline



path = 'drive/My Drive/DevC/'

chc = pd.read_csv('drive/My Drive/DevC/ChungCu.csv')
chc.head(1)

chc.linkProject[0]

chc.describe()

chc.info()

chc.isnull().sum()

acreage=chc['acreage'].str.extract('(\d+.?\d*)').astype(float)
acreage.isnull().sum()
#bỏ m2 trên acreage chuyển sang dạng số

chc['acreage'] = acreage
#thay gia chi ở col acreage bang gia tri mới

typrice = chc['price'].str.contains("tỷ")
#lay gia tri co chu ty ra

trieuprice = chc['price'].str.endswith('iệu')

floattyprice = chc[typrice]['price'].str.extract('(\d+.?\d*)').astype(float)*1000
#Lay tu typrice ra va *1000 de tinh sang trieu

pricetom=floattyprice.div(chc[typrice][['acreage']].values)
#quy tien ty ve tien trieu

chc['pricePerM'] = chc['price'].copy()
#copy ra 1 col moi

chc['pricePerM'] = chc['pricePerM'].str.extract('(\d+.?\d*)').astype(float)
#covert bang ve so

chc['pricePerM'].update(pricetom[0])
#update la bang pricetom bang gia/m

giatrieu=chc[trieuprice&(chc['pricePerM']>200)]['pricePerM']
trieuToM= giatrieu.div(chc[trieuprice&(chc['pricePerM']>200)]['acreage'].values)

chc['pricePerM'].update(trieuToM)

chc[['price','pricePerM']].iloc[75]

numBathroom = chc['numBathroom'].str.extract('(\d+)').astype(float)
numBedroom = chc['numBedroom'].str.extract('(\d+)').astype(float)

chc['numBathroom'] = numBathroom
chc['numBedroom'] = numBedroom

chc['pricePerM'].isnull().sum()

locations = chc.location.str.strip('[]').str.split(',')

latitude =  []
longitude = []
for i in locations:
    latitude.append(float(i[0]))
    longitude.append(float(i[1]))

chc['lat']=latitude
chc['long'] = longitude

chc['date'] = pd.to_datetime(chc['date'],dayfirst=True)

chc['quarters'] = chc['date'].dt.quarter
#Thêm quý trong năm

chc[['price','acreage']].info()

chc[(chc['pricePerM'].isnull()) & (chc['price'].str.contains('thuận'))][['pricePerM','price','acreage']].index

df=chc.drop(columns=['service','facade','wayIn','contact','linkProject','location'])

df = df.drop(df[df['pricePerM'].isnull()][['pricePerM','price','acreage']].index)

df[df['pricePerM'].isnull()][['pricePerM','price','acreage']]

df.to_csv(path+'DataPxK_1.csv',index=False)

df.describe()

df = df.reset_index().drop(columns=['index'])

df.info()

